language: python
python:
- '2.7'
script: ./unittests
deploy:
  provider: lambda
  function_name: CherieSkill
  region: us-east-1
  role: arn:aws:iam::545869610442:role/lambda_basic_execution
  runtime: python2.7
  module_name: alexa_py
  handler_name: lambda_handler
  zip: "./src"
  access_key_id: AKIAJMPONK766NXLBV6A
  on:
    branch: master
  secret_access_key:
    secure: NBKb3Jhe+l41wYDm3n2XMLsUaL2Xh2yxzwFvqYFw1JSD5CvM97J39raig0IW/FQImcXBQ2dxx/6VLxgZu15Z+mJwVb4GCunxX7/RByrPG6bS/ibdEGet8SvEcbf/tXUvmqcU6NaXi75/QLqwPhvoS1KP4OICm3vYGF3FdG7X5WMlFIi+U4NX53kAkWAdwgDp2eWphcdJcJGH2l8qdS8wMb958m1nNa0gWmF1Z16oOltoIg+6+dPQujzTjJPAp/N6VCi4jlvCho+IcnxiUVj7yFUBUC5ppGkx9XCuOiuc9GaO4zN6pZHRZYQCAG5kSjV4aSfKWW7vk0dLwgEKmn1nqZVPAvyemtj4dGcy/gCitguyeM/267mi7q/cEN7AKIBWTBrvLABvaMfxKlXpQeoYSihyxzEg0ES1b6qndQDpVHlSED+uqOEqIPTZESQXmR1OCHCBajQcPgO+cr68f5VgFQvLFEHhZt11ia/ywRcYFuf5DBnGQiFZYltF5WtSqK+vEDRrSVKWLA37ElPyf9CyVud5EODjyu6ub5Vg3is42AhOu/bYBMPHASmWCdwP409U6p6Rf4W5LmnrIQBQXAZKsYcON+gWd2uc2ENYcmPsJ+BSw6AHh30JhgI9OIOBWRlN9pkklUYNOJaOhM/ObULh/XbHAntgHIqeLylfeFqsyFU=
